#!/bin/sh
# uname(1) simulator, inspired by Pavel Roskin.

[ $1 = -m ] && echo ia64 && exit 0
[ $1 = -r ] && echo B.11.20 && exit 0
[ $1 = -s ] && echo HP-UX && exit 0
[ $1 = -v ] && echo A && exit 0
